<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 0" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\python-generated\generate-mongoDB\generate-mongoDB.py" status="error" test="generate-mongoDB" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "D:\program files\Developer Tools\eclipse-oxygen\plugins\org.python.pydev_6.2.0.201711281614\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "D:/Project/GitHub/recommendation_system/SSF/movie-recommendation/src/python-generated/generate-mongoDB\generate-mongoDB.py", line 44, in <module>
    row[field]=each[field]
KeyError: 'userId'
ERROR: Module: generate-mongoDB could not be imported (file: D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\python-generated\generate-mongoDB\generate-mongoDB.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="movie-recommendation generate-mongoDB.py (1)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
